Repository cypress-io/github-action, pull requests merged in 2025-03, with the labels that each got.

#1381 test: remove default video: false configuration item
  examples/browser/cypress.config.js
  examples/component-tests/cypress.config.js
Labels: tests

#1385 test: extend cypress examples linting to javascript styles
  .prettierignore
  eslint.config.mjs
  examples/browser/cypress.config.js
  examples/browser/cypress/e2e/spec.cy.js
  examples/component-tests/cypress.config.js
  examples/config/cypress.config-alternate.js
  examples/config/cypress/e2e/spec-a.cy.js
  examples/config/cypress/e2e/spec-b.cy.js
  examples/custom-command/index.js
  examples/env/cypress.config.js
  examples/env/cypress/e2e/spec.cy.js
  examples/env/cypress/e2e/without-env.cy.js
  examples/nextjs/cypress.config.js
  examples/quiet/cypress.config.js
  examples/quiet/cypress/e2e/spec.cy.js
  examples/wait-on/index.js
  examples/wait-on/index2.js
  examples/wait-on/index3.js
  examples/wait-on/index4.js
  examples/webpack/webpack.config.js
  package-lock.json
  package.json
Labels: tests, ci

#1371 fix: Use correct baseUrl when running in non-public Github instances
  dist/index.js
  index.js
Labels: bug, Cypress Cloud

#1386 test: prettier format example yml workflows
  .github/workflows/example-basic-pnpm.yml
  .github/workflows/example-basic.yml
  .github/workflows/example-chrome.yml
  .github/workflows/example-config.yml
  .github/workflows/example-custom-ci-build-id.yml
  .github/workflows/example-custom-command.yml
  .github/workflows/example-env.yml
  .github/workflows/example-firefox.yml
  .github/workflows/example-install-command.yml
  .github/workflows/example-install-only.yml
  .github/workflows/example-node-versions.yml
  .github/workflows/example-quiet.yml
  .github/workflows/example-recording.yml
  .github/workflows/example-start-and-pnpm-workspaces.yml
  .github/workflows/example-start-and-yarn-workspaces.yml
  .github/workflows/example-start.yml
  .github/workflows/example-wait-on.yml
  .github/workflows/example-webpack.yml
  .github/workflows/example-yarn-classic.yml
  .github/workflows/example-yarn-modern-pnp.yml
  .github/workflows/example-yarn-modern.yml
  .prettierignore
Labels: tests, ci

#1389 test: prettier format example json files
  .prettierignore
  examples/start-and-pnpm-workspaces/package.json
Labels: tests, ci

#1394 ci: self-lint eslint config style
  .prettierignore
  eslint.config.mjs
Labels: ci

#1395 fix: pass baseUrl into Octokit constructor
  dist/index.js
  index.js
Labels: bug, Cypress Cloud

#1396 ci: exclude builds from eslint checks
  eslint.config.mjs
Labels: ci

#1397 test: add jsx linting
  .prettierignore
  examples/component-tests/src/components/Stepper.jsx
Labels: tests

#1398 ci: exclude prettier checks on generated content
  .prettierignore
Labels: ci

#1399 ci: add overall prettier check to ci
  .github/workflows/main.yml
  CONTRIBUTING.md
  package.json
Labels: documentation, ci

#1400 chore(deps): update cypress to 14.2.0
  .github/workflows/example-install-only.yml
  examples/basic-pnpm/package.json
  examples/basic-pnpm/pnpm-lock.yaml
  examples/basic/package-lock.json
  examples/basic/package.json
  examples/browser/package-lock.json
  examples/browser/package.json
  examples/component-tests/package-lock.json
  examples/component-tests/package.json
  examples/config/package-lock.json
  examples/config/package.json
  examples/custom-command/package-lock.json
  examples/custom-command/package.json
  examples/env/package-lock.json
  examples/env/package.json
  examples/install-command/package.json
  examples/install-command/yarn.lock
  examples/install-only/package-lock.json
  examples/install-only/package.json
  examples/nextjs/package-lock.json
  examples/nextjs/package.json
  examples/node-versions/package-lock.json
  examples/node-versions/package.json
  examples/quiet/package-lock.json
  examples/quiet/package.json
  examples/recording/package-lock.json
  examples/recording/package.json
  examples/start-and-pnpm-workspaces/packages/workspace-1/package.json
  examples/start-and-pnpm-workspaces/packages/workspace-2/package.json
  examples/start-and-pnpm-workspaces/pnpm-lock.yaml
  examples/start-and-yarn-workspaces/workspace-1/package.json
  examples/start-and-yarn-workspaces/workspace-2/package.json
  examples/start-and-yarn-workspaces/yarn.lock
  examples/start/package-lock.json
  examples/start/package.json
  examples/wait-on-vite/package-lock.json
  examples/wait-on-vite/package.json
  examples/wait-on/package-lock.json
  examples/wait-on/package.json
  examples/webpack/package-lock.json
  examples/webpack/package.json
  examples/yarn-classic/package.json
  examples/yarn-classic/yarn.lock
  examples/yarn-modern-pnp/package.json
  examples/yarn-modern-pnp/yarn.lock
  examples/yarn-modern/package.json
  examples/yarn-modern/yarn.lock
Labels: type: dependencies

#1404 docs: re-align external repo example table
  README.md
Labels: documentation

#1405 docs: add README caching section
  README.md
Labels: documentation

#1411 test(deps): update next to 15.2.3
  examples/nextjs/package-lock.json
  examples/nextjs/package.json
Labels: type: dependencies, tests

#1412 docs: fix example status badge in contributing
  CONTRIBUTING.md
Labels: documentation

#1413 chore: add script lint:fix
  CONTRIBUTING.md
  package.json
Labels: documentation

#1415 chore(deps): update cypress to 14.2.1
  .github/workflows/example-install-only.yml
  examples/basic-pnpm/package.json
  examples/basic-pnpm/pnpm-lock.yaml
  examples/basic/package-lock.json
  examples/basic/package.json
  examples/browser/package-lock.json
  examples/browser/package.json
  examples/component-tests/package-lock.json
  examples/component-tests/package.json
  examples/config/package-lock.json
  examples/config/package.json
  examples/custom-command/package-lock.json
  examples/custom-command/package.json
  examples/env/package-lock.json
  examples/env/package.json
  examples/install-command/package.json
  examples/install-command/yarn.lock
  examples/install-only/package-lock.json
  examples/install-only/package.json
  examples/nextjs/package-lock.json
  examples/nextjs/package.json
  examples/node-versions/package-lock.json
  examples/node-versions/package.json
  examples/quiet/package-lock.json
  examples/quiet/package.json
  examples/recording/package-lock.json
  examples/recording/package.json
  examples/start-and-pnpm-workspaces/packages/workspace-1/package.json
  examples/start-and-pnpm-workspaces/packages/workspace-2/package.json
  examples/start-and-pnpm-workspaces/pnpm-lock.yaml
  examples/start-and-yarn-workspaces/workspace-1/package.json
  examples/start-and-yarn-workspaces/workspace-2/package.json
  examples/start-and-yarn-workspaces/yarn.lock
  examples/start/package-lock.json
  examples/start/package.json
  examples/wait-on-vite/package-lock.json
  examples/wait-on-vite/package.json
  examples/wait-on/package-lock.json
  examples/wait-on/package.json
  examples/webpack/package-lock.json
  examples/webpack/package.json
  examples/yarn-classic/package.json
  examples/yarn-classic/yarn.lock
  examples/yarn-modern-pnp/package.json
  examples/yarn-modern-pnp/yarn.lock
  examples/yarn-modern/package.json
  examples/yarn-modern/yarn.lock
Labels: type: dependencies

#1417 chore: add debug output of node.js version
  dist/index.js
  index.js
Labels: type: enhancement
